# Generated by Django 2.2 on 2021-05-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0005_auto_20210525_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Post'),
        ),
    ]
